### PR TITLE
Add META.json to distribution

### PR DESCRIPTION
**Pull request by paultcochrane**
This fixes the currently-shown extra issue on [CPANTS](http://cpants.cpanauthors.org/dist/Unicode-CaseFold) as well as resolves bug RT#108114.

### CODE REVIEW

**Comment by arodland** [comment]
Added to PluginBundle::ARODLAND so that all my modules get it, instead of doing it here. I will do a release soonish

**Comment by paultcochrane** [comment]
Ok, good to know.  It might be a good idea to hold off on releasing for a bit as I've got a couple of other PRs in the works at present.

**Comment by paultcochrane** [comment]
Hrm, I just upgraded your plugin bundle so that I have the most recent changes and now `dzil test` doesn't work anymore:

```
[DZ] attempt to add Build.PL multiple times; added by: content added by @ARODLAND/ModuleBuildTiny (Dist::Zilla::Plugin::ModuleBuildTiny line 130); content set by ModuleBuildTiny (Dist::Zilla::Plugin::ModuleBuildTiny line 155); content set by ModuleBuild (Dist::Zilla::Plugin::ModuleBuild line 232); content set by ModuleBuild::OptionalXS (Dist::Zilla::Plugin::ModuleBuild::OptionalXS line 33); content added by ModuleBuild::OptionalXS (Dist::Zilla::Plugin::ModuleBuild line 200)
```

Any idea what's going on there?

I was trying to work out why after the `README` had been produced by a previous run, that its presence blocked following test (or build) runs (it was necessary to explicitly remove the README before `dzil test` or `dzil build` would run again).  The problem here seemed to come from the `CopyFilesFromBuild` plugin:

```
[@ARODLAND/CopyFilesFromBuild] Cannot copy README from build: file does not exist
```

... although the error message doesn't match the symptom: the README *exists* and causes the build to fail.  Any idea what might have been causing that?

**Comment by paultcochrane** [comment]
My apologies: the ModuleBuild issue I mention above was fixed after merging with your most recent changes.  So it seems that issue was just PEBKAC. :-/  Your recent `dist.ini` update also fixed the README issue, so now everything's working nicely :-)

**Pull request closed without merging**
